name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Generar carpeta Android del proyecto
        run: flutter create --platforms=android --project-name sotelux_app .

      - name: Actualizar versión de Kotlin
        run: sed -i 's/org.jetbrains.kotlin.android" version "[^"]*"/org.jetbrains.kotlin.android" version "1.9.22"/' android/settings.gradle

      - name: Instalar dependencias
        run: flutter pub get

      - name: Generar ícono de la app
        run: dart run flutter_launcher_icons

      - name: Compilar APK
        run: flutter build apk --release

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: sotelux-app-apk
          path: build/app/outputs/flutter-apk/app-release.apk
